apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: glm-zhu
  namespace: zhu-dev
  labels:
    app.kubernetes.io/name: glm-zhu-epp
    app.kubernetes.io/version: v0.9.0
spec:
  targetPorts:
  - number: 8000
  - number: 8001
  - number: 8002
  - number: 8003
  - number: 8004
  - number: 8005
  - number: 8006
  - number: 8007
  appProtocol: http
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: 'true'
      llm-d.ai/owner: zhu
  endpointPickerRef:
    name: glm-zhu-epp
    port:
      number: 9002
    failureMode: FailOpen
